name: 'GitHub Actions Analyzer'
description: 'Analyzes GitHub Actions workflow performance and provides optimization recommendations'
inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  workflow_file:
    description: 'Workflow file to analyze'
    required: true
  repository:
    description: 'Repository to analyze (format: owner/repo)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    WORKFLOW_FILE: ${{ inputs.workflow_file }}
    REPOSITORY: ${{ inputs.repository }}
