name: 'GitHub Actions Analyzer'

description: 'Analyzes GitHub Actions workflow performance and provides optimization recommendations'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  workflow_file:
    description: 'Workflow file to analyze'
    required: true
  repository:
    description: 'Repository to analyze (format: owner/repo)'
    required: true
  debug:
    description: 'Enable debug mode'
    required: false
  analysis_depth:
    description: 'Number of workflow runs to analyze (default: 10)'
    required: false
    default: '10'
  ignore_patterns:
    description: 'Comma-separated list of step names to ignore in analysis'
    required: false
  timeout:
    description: 'Analysis timeout in minutes (default: 60)'
    required: false
    default: '60'

outputs:
  metrics_summary:
    description: 'Summary of workflow metrics in JSON format'
  performance_summary:
    description: 'Detailed performance analysis summary'
  cache_recommendations:
    description: 'Cache optimization recommendations'
  docker_optimizations:
    description: 'Docker-related optimization suggestions'
  status:
    description: 'Analysis execution status'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    WORKFLOW_FILE: ${{ inputs.workflow_file }}
    REPOSITORY: ${{ inputs.repository }}
    DEBUG: ${{ inputs.debug }}
    ANALYSIS_DEPTH: ${{ inputs.analysis_depth }}
    IGNORE_PATTERNS: ${{ inputs.ignore_patterns }}
    TIMEOUT: ${{ inputs.timeout }}

branding:
  icon: 'activity'
  color: 'blue'