name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '**/*.md'
      - 'backup/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  analyze:
    name: Analyze Workflow
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Performance Analysis
        id: analyzer
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file: ci.yml
          repository: ${{ github.repository }}

      - name: Display Analysis Results
        run: |
          echo "Performance Summary: ${{ steps.analyzer.outputs.performance_summary }}"
          echo "Cache Recommendations: ${{ steps.analyzer.outputs.cache_recommendations }}"
          echo "Docker Optimizations: ${{ steps.analyzer.outputs.docker_optimizations }}"
          echo "Status: ${{ steps.analyzer.outputs.status }}"

  analyze-test-workflow:
    name: Analyze Test Workflow
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Performance Analysis
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file: test-languages-workflow.yml
          repository: ${{ github.repository }}

  analyze-target:
    name: Analyze Target Workflow
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Performance Analysis
        id: analyzer
        uses: ./
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file: ci.yml
          repository: somaz94/compress-decompress