name: Test Workflow (Inefficient)

on:
  workflow_dispatch:

jobs:
  test-slow-workflow:
    name: Test Workflow with Inefficiencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 의도적으로 비효율적인 Docker 빌드 (캐시 미사용)
      - name: Inefficient Docker Build
        run: |
          docker build --no-cache -t test-image .

      # 의도적으로 중복된 의존성 설치
      - name: Redundant Dependencies
        run: |
          go mod download
          go mod download
          go mod download

      # 의도적인 지연
      - name: Artificial Delay
        run: sleep 30

      # 캐시를 사용하지 않는 작업
      - name: No Cache Usage
        run: |
          rm -rf ~/.cache/go-build
          go build ./...

      # 불필요한 Docker 이미지 빌드
      - name: Unnecessary Rebuilds
        run: |
          docker build -t test-image:1 .
          docker build -t test-image:2 .
          docker build -t test-image:3 .


