name: Test Languages Workflow

on:
  workflow_dispatch:

jobs:
  test-go:
    name: Test Go Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # 의도적으로 이전 버전 사용

      - name: Go Build (캐시 미사용)
        run: |
          rm -rf ~/.cache/go-build
          go build ./...

      - name: Go Test
        run: go test ./...

  test-node:
    name: Test Node.js Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # 의도적으로 이전 버전 사용

      - name: NPM Install (캐시 미사용)
        run: |
          rm -rf ~/.npm
          npm install

      - name: NPM Build
        run: npm run build

  test-python:
    name: Test Python Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 의도적으로 이전 버전 사용

      - name: Install Dependencies (캐시 미사용)
        run: |
          rm -rf ~/.cache/pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest

  test-java:
    name: Test Java Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # 의도적으로 이전 버전 사용
          distribution: 'temurin'

      - name: Build with Maven (캐시 미사용)
        run: |
          rm -rf ~/.m2/repository
          mvn clean install

      - name: Run Tests
        run: mvn test

  test-ruby:
    name: Test Ruby Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # 의도적으로 이전 버전 사용

      - name: Install Dependencies (캐시 미사용)
        run: |
          rm -rf vendor/bundle
          bundle install

      - name: Run Tests
        run: bundle exec rake test

  test-rust:
    name: Test Rust Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@1.100.0  # 의도적으로 이전 버전 사용

      - name: Build (캐시 미사용)
        run: |
          rm -rf ~/.cargo/registry
          cargo build

      - name: Run Tests
        run: cargo test

  test-dotnet:
    name: Test .NET Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'  # 의도적으로 이전 버전 사용

      - name: Restore Dependencies (캐시 미사용)
        run: |
          rm -rf ~/.nuget/packages
          dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build